version: '3.1'
services:
  library-postgres:
    image: postgres:14
    container_name: library-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: library-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

networks:
  keycloak-network: